name: Test logic and interface

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm run setup
    - name: Test logic
      run: npm run test -- --ci
    - name: Test interface
      run: npm run build --ci && npx start-server-and-test start 3000 'olsk-spec-ui --ci'
